### ISSUE TITLE
Console Errors

### ISSUE THREAD

**Issue by Instinkt-Servers** [Bitverbieger/SurvivorMissions#3]
CRIPT    (E): NULL pointer to instance
Class:      'HordeMission'
Function: 'MissionFinal'
Stack trace:
$CurrentDir://mpmissions//Expansion.ChernarusPlus//SurvivorMissionModule//Missions//Horde.c:382
SurvivorMissions/scripts/5_Mission/missionserver\чю?о..c:661
SurvivorMissions/scripts/5_Mission/missionserver\чю?о..c:307
SurvivorMissions/scripts/5_Mission/missionserver\щх?ЩйќмС..c:138
SurvivorMissions/scripts/5_Mission/missionserver\щх?ЩйќмС..c:102
scripts/5_Mission/mission\missionserver.c:45
TM/Trader/scripts/5_Mission/mission\missionserver.c:80
JM/CF/Scripts/5_Mission/communityframework\mission\missionserver.c:66
JM/COT/Scripts/5_Mission/communityonlinetools\missionserver.c:39
scripts/3_Game/dayzgame.c:2326
DayZExpansion/Core/3_Game/dayzexpansion_core\dayzgame.c:203

**Comment by Bitverbieger** [comment]
If you didn't change the code it might be the Infected-Alert function.
In this case deactivate line 376 - 384. The problem will be resolved in the next gh update!
